// const defaultFollowing = [
//   {
//     "login": "lawrence254",
//     "id": 7699924,
//     "node_id": "MDQ6VXNlcjc2OTk5MjQ=",
//     "avatar_url": "https://avatars3.githubusercontent.com/u/7699924?v=4",
//     "gravatar_id": "",
//     "url": "https://api.github.com/users/lawrence254",
//     "html_url": "https://github.com/lawrence254",
//     "followers_url": "https://api.github.com/users/lawrence254/followers",
//     "following_url": "https://api.github.com/users/lawrence254/following{/other_user}",
//     "gists_url": "https://api.github.com/users/lawrence254/gists{/gist_id}",
//     "starred_url": "https://api.github.com/users/lawrence254/starred{/owner}{/repo}",
//     "subscriptions_url": "https://api.github.com/users/lawrence254/subscriptions",
//     "organizations_url": "https://api.github.com/users/lawrence254/orgs",
//     "repos_url": "https://api.github.com/users/lawrence254/repos",
//     "events_url": "https://api.github.com/users/lawrence254/events{/privacy}",
//     "received_events_url": "https://api.github.com/users/lawrence254/received_events",
//     "type": "User",
//     "site_admin": false
//   },
//   {
//     "login": "melisamalala",
//     "id": 8698086,
//     "node_id": "MDQ6VXNlcjg2OTgwODY=",
//     "avatar_url": "https://avatars2.githubusercontent.com/u/8698086?v=4",
//     "gravatar_id": "",
//     "url": "https://api.github.com/users/melisamalala",
//     "html_url": "https://github.com/melisamalala",
//     "followers_url": "https://api.github.com/users/melisamalala/followers",
//     "following_url": "https://api.github.com/users/melisamalala/following{/other_user}",
//     "gists_url": "https://api.github.com/users/melisamalala/gists{/gist_id}",
//     "starred_url": "https://api.github.com/users/melisamalala/starred{/owner}{/repo}",
//     "subscriptions_url": "https://api.github.com/users/melisamalala/subscriptions",
//     "organizations_url": "https://api.github.com/users/melisamalala/orgs",
//     "repos_url": "https://api.github.com/users/melisamalala/repos",
//     "events_url": "https://api.github.com/users/melisamalala/events{/privacy}",
//     "received_events_url": "https://api.github.com/users/melisamalala/received_events",
//     "type": "User",
//     "site_admin": false
//   },
//   {
//     "login": "DevWaweru",
//     "id": 11243592,
//     "node_id": "MDQ6VXNlcjExMjQzNTky",
//     "avatar_url": "https://avatars2.githubusercontent.com/u/11243592?v=4",
//     "gravatar_id": "",
//     "url": "https://api.github.com/users/DevWaweru",
//     "html_url": "https://github.com/DevWaweru",
//     "followers_url": "https://api.github.com/users/DevWaweru/followers",
//     "following_url": "https://api.github.com/users/DevWaweru/following{/other_user}",
//     "gists_url": "https://api.github.com/users/DevWaweru/gists{/gist_id}",
//     "starred_url": "https://api.github.com/users/DevWaweru/starred{/owner}{/repo}",
//     "subscriptions_url": "https://api.github.com/users/DevWaweru/subscriptions",
//     "organizations_url": "https://api.github.com/users/DevWaweru/orgs",
//     "repos_url": "https://api.github.com/users/DevWaweru/repos",
//     "events_url": "https://api.github.com/users/DevWaweru/events{/privacy}",
//     "received_events_url": "https://api.github.com/users/DevWaweru/received_events",
//     "type": "User",
//     "site_admin": false
//   },
//   {
//     "login": "davidlutta",
//     "id": 14890315,
//     "node_id": "MDQ6VXNlcjE0ODkwMzE1",
//     "avatar_url": "https://avatars2.githubusercontent.com/u/14890315?v=4",
//     "gravatar_id": "",
//     "url": "https://api.github.com/users/davidlutta",
//     "html_url": "https://github.com/davidlutta",
//     "followers_url": "https://api.github.com/users/davidlutta/followers",
//     "following_url": "https://api.github.com/users/davidlutta/following{/other_user}",
//     "gists_url": "https://api.github.com/users/davidlutta/gists{/gist_id}",
//     "starred_url": "https://api.github.com/users/davidlutta/starred{/owner}{/repo}",
//     "subscriptions_url": "https://api.github.com/users/davidlutta/subscriptions",
//     "organizations_url": "https://api.github.com/users/davidlutta/orgs",
//     "repos_url": "https://api.github.com/users/davidlutta/repos",
//     "events_url": "https://api.github.com/users/davidlutta/events{/privacy}",
//     "received_events_url": "https://api.github.com/users/davidlutta/received_events",
//     "type": "User",
//     "site_admin": false
//   },
//   {
//     "login": "kimani-njoroge",
//     "id": 16648053,
//     "node_id": "MDQ6VXNlcjE2NjQ4MDUz",
//     "avatar_url": "https://avatars1.githubusercontent.com/u/16648053?v=4",
//     "gravatar_id": "",
//     "url": "https://api.github.com/users/kimani-njoroge",
//     "html_url": "https://github.com/kimani-njoroge",
//     "followers_url": "https://api.github.com/users/kimani-njoroge/followers",
//     "following_url": "https://api.github.com/users/kimani-njoroge/following{/other_user}",
//     "gists_url": "https://api.github.com/users/kimani-njoroge/gists{/gist_id}",
//     "starred_url": "https://api.github.com/users/kimani-njoroge/starred{/owner}{/repo}",
//     "subscriptions_url": "https://api.github.com/users/kimani-njoroge/subscriptions",
//     "organizations_url": "https://api.github.com/users/kimani-njoroge/orgs",
//     "repos_url": "https://api.github.com/users/kimani-njoroge/repos",
//     "events_url": "https://api.github.com/users/kimani-njoroge/events{/privacy}",
//     "received_events_url": "https://api.github.com/users/kimani-njoroge/received_events",
//     "type": "User",
//     "site_admin": false
//   },
//   {
//     "login": "muturi254",
//     "id": 18753917,
//     "node_id": "MDQ6VXNlcjE4NzUzOTE3",
//     "avatar_url": "https://avatars1.githubusercontent.com/u/18753917?v=4",
//     "gravatar_id": "",
//     "url": "https://api.github.com/users/muturi254",
//     "html_url": "https://github.com/muturi254",
//     "followers_url": "https://api.github.com/users/muturi254/followers",
//     "following_url": "https://api.github.com/users/muturi254/following{/other_user}",
//     "gists_url": "https://api.github.com/users/muturi254/gists{/gist_id}",
//     "starred_url": "https://api.github.com/users/muturi254/starred{/owner}{/repo}",
//     "subscriptions_url": "https://api.github.com/users/muturi254/subscriptions",
//     "organizations_url": "https://api.github.com/users/muturi254/orgs",
//     "repos_url": "https://api.github.com/users/muturi254/repos",
//     "events_url": "https://api.github.com/users/muturi254/events{/privacy}",
//     "received_events_url": "https://api.github.com/users/muturi254/received_events",
//     "type": "User",
//     "site_admin": false
//   },
//   {
//     "login": "Ngahu",
//     "id": 19609166,
//     "node_id": "MDQ6VXNlcjE5NjA5MTY2",
//     "avatar_url": "https://avatars3.githubusercontent.com/u/19609166?v=4",
//     "gravatar_id": "",
//     "url": "https://api.github.com/users/Ngahu",
//     "html_url": "https://github.com/Ngahu",
//     "followers_url": "https://api.github.com/users/Ngahu/followers",
//     "following_url": "https://api.github.com/users/Ngahu/following{/other_user}",
//     "gists_url": "https://api.github.com/users/Ngahu/gists{/gist_id}",
//     "starred_url": "https://api.github.com/users/Ngahu/starred{/owner}{/repo}",
//     "subscriptions_url": "https://api.github.com/users/Ngahu/subscriptions",
//     "organizations_url": "https://api.github.com/users/Ngahu/orgs",
//     "repos_url": "https://api.github.com/users/Ngahu/repos",
//     "events_url": "https://api.github.com/users/Ngahu/events{/privacy}",
//     "received_events_url": "https://api.github.com/users/Ngahu/received_events",
//     "type": "User",
//     "site_admin": false
//   },
//   {
//     "login": "EKibet",
//     "id": 20268029,
//     "node_id": "MDQ6VXNlcjIwMjY4MDI5",
//     "avatar_url": "https://avatars3.githubusercontent.com/u/20268029?v=4",
//     "gravatar_id": "",
//     "url": "https://api.github.com/users/EKibet",
//     "html_url": "https://github.com/EKibet",
//     "followers_url": "https://api.github.com/users/EKibet/followers",
//     "following_url": "https://api.github.com/users/EKibet/following{/other_user}",
//     "gists_url": "https://api.github.com/users/EKibet/gists{/gist_id}",
//     "starred_url": "https://api.github.com/users/EKibet/starred{/owner}{/repo}",
//     "subscriptions_url": "https://api.github.com/users/EKibet/subscriptions",
//     "organizations_url": "https://api.github.com/users/EKibet/orgs",
//     "repos_url": "https://api.github.com/users/EKibet/repos",
//     "events_url": "https://api.github.com/users/EKibet/events{/privacy}",
//     "received_events_url": "https://api.github.com/users/EKibet/received_events",
//     "type": "User",
//     "site_admin": false
//   },
//   {
//     "login": "SophiaNM",
//     "id": 20294491,
//     "node_id": "MDQ6VXNlcjIwMjk0NDkx",
//     "avatar_url": "https://avatars0.githubusercontent.com/u/20294491?v=4",
//     "gravatar_id": "",
//     "url": "https://api.github.com/users/SophiaNM",
//     "html_url": "https://github.com/SophiaNM",
//     "followers_url": "https://api.github.com/users/SophiaNM/followers",
//     "following_url": "https://api.github.com/users/SophiaNM/following{/other_user}",
//     "gists_url": "https://api.github.com/users/SophiaNM/gists{/gist_id}",
//     "starred_url": "https://api.github.com/users/SophiaNM/starred{/owner}{/repo}",
//     "subscriptions_url": "https://api.github.com/users/SophiaNM/subscriptions",
//     "organizations_url": "https://api.github.com/users/SophiaNM/orgs",
//     "repos_url": "https://api.github.com/users/SophiaNM/repos",
//     "events_url": "https://api.github.com/users/SophiaNM/events{/privacy}",
//     "received_events_url": "https://api.github.com/users/SophiaNM/received_events",
//     "type": "User",
//     "site_admin": false
//   },
//   {
//     "login": "wanjiiru",
//     "id": 20424355,
//     "node_id": "MDQ6VXNlcjIwNDI0MzU1",
//     "avatar_url": "https://avatars3.githubusercontent.com/u/20424355?v=4",
//     "gravatar_id": "",
//     "url": "https://api.github.com/users/wanjiiru",
//     "html_url": "https://github.com/wanjiiru",
//     "followers_url": "https://api.github.com/users/wanjiiru/followers",
//     "following_url": "https://api.github.com/users/wanjiiru/following{/other_user}",
//     "gists_url": "https://api.github.com/users/wanjiiru/gists{/gist_id}",
//     "starred_url": "https://api.github.com/users/wanjiiru/starred{/owner}{/repo}",
//     "subscriptions_url": "https://api.github.com/users/wanjiiru/subscriptions",
//     "organizations_url": "https://api.github.com/users/wanjiiru/orgs",
//     "repos_url": "https://api.github.com/users/wanjiiru/repos",
//     "events_url": "https://api.github.com/users/wanjiiru/events{/privacy}",
//     "received_events_url": "https://api.github.com/users/wanjiiru/received_events",
//     "type": "User",
//     "site_admin": false
//   },
//   {
//     "login": "lucasLB7",
//     "id": 24963171,
//     "node_id": "MDQ6VXNlcjI0OTYzMTcx",
//     "avatar_url": "https://avatars2.githubusercontent.com/u/24963171?v=4",
//     "gravatar_id": "",
//     "url": "https://api.github.com/users/lucasLB7",
//     "html_url": "https://github.com/lucasLB7",
//     "followers_url": "https://api.github.com/users/lucasLB7/followers",
//     "following_url": "https://api.github.com/users/lucasLB7/following{/other_user}",
//     "gists_url": "https://api.github.com/users/lucasLB7/gists{/gist_id}",
//     "starred_url": "https://api.github.com/users/lucasLB7/starred{/owner}{/repo}",
//     "subscriptions_url": "https://api.github.com/users/lucasLB7/subscriptions",
//     "organizations_url": "https://api.github.com/users/lucasLB7/orgs",
//     "repos_url": "https://api.github.com/users/lucasLB7/repos",
//     "events_url": "https://api.github.com/users/lucasLB7/events{/privacy}",
//     "received_events_url": "https://api.github.com/users/lucasLB7/received_events",
//     "type": "User",
//     "site_admin": false
//   },
//   {
//     "login": "adiela",
//     "id": 25149509,
//     "node_id": "MDQ6VXNlcjI1MTQ5NTA5",
//     "avatar_url": "https://avatars2.githubusercontent.com/u/25149509?v=4",
//     "gravatar_id": "",
//     "url": "https://api.github.com/users/adiela",
//     "html_url": "https://github.com/adiela",
//     "followers_url": "https://api.github.com/users/adiela/followers",
//     "following_url": "https://api.github.com/users/adiela/following{/other_user}",
//     "gists_url": "https://api.github.com/users/adiela/gists{/gist_id}",
//     "starred_url": "https://api.github.com/users/adiela/starred{/owner}{/repo}",
//     "subscriptions_url": "https://api.github.com/users/adiela/subscriptions",
//     "organizations_url": "https://api.github.com/users/adiela/orgs",
//     "repos_url": "https://api.github.com/users/adiela/repos",
//     "events_url": "https://api.github.com/users/adiela/events{/privacy}",
//     "received_events_url": "https://api.github.com/users/adiela/received_events",
//     "type": "User",
//     "site_admin": false
//   },
//   {
//     "login": "jakhax",
//     "id": 27997774,
//     "node_id": "MDQ6VXNlcjI3OTk3Nzc0",
//     "avatar_url": "https://avatars2.githubusercontent.com/u/27997774?v=4",
//     "gravatar_id": "",
//     "url": "https://api.github.com/users/jakhax",
//     "html_url": "https://github.com/jakhax",
//     "followers_url": "https://api.github.com/users/jakhax/followers",
//     "following_url": "https://api.github.com/users/jakhax/following{/other_user}",
//     "gists_url": "https://api.github.com/users/jakhax/gists{/gist_id}",
//     "starred_url": "https://api.github.com/users/jakhax/starred{/owner}{/repo}",
//     "subscriptions_url": "https://api.github.com/users/jakhax/subscriptions",
//     "organizations_url": "https://api.github.com/users/jakhax/orgs",
//     "repos_url": "https://api.github.com/users/jakhax/repos",
//     "events_url": "https://api.github.com/users/jakhax/events{/privacy}",
//     "received_events_url": "https://api.github.com/users/jakhax/received_events",
//     "type": "User",
//     "site_admin": false
//   },
//   {
//     "login": "Blankphrase",
//     "id": 28699640,
//     "node_id": "MDQ6VXNlcjI4Njk5NjQw",
//     "avatar_url": "https://avatars1.githubusercontent.com/u/28699640?v=4",
//     "gravatar_id": "",
//     "url": "https://api.github.com/users/Blankphrase",
//     "html_url": "https://github.com/Blankphrase",
//     "followers_url": "https://api.github.com/users/Blankphrase/followers",
//     "following_url": "https://api.github.com/users/Blankphrase/following{/other_user}",
//     "gists_url": "https://api.github.com/users/Blankphrase/gists{/gist_id}",
//     "starred_url": "https://api.github.com/users/Blankphrase/starred{/owner}{/repo}",
//     "subscriptions_url": "https://api.github.com/users/Blankphrase/subscriptions",
//     "organizations_url": "https://api.github.com/users/Blankphrase/orgs",
//     "repos_url": "https://api.github.com/users/Blankphrase/repos",
//     "events_url": "https://api.github.com/users/Blankphrase/events{/privacy}",
//     "received_events_url": "https://api.github.com/users/Blankphrase/received_events",
//     "type": "User",
//     "site_admin": false
//   },
//   {
//     "login": "newtonmunene99",
//     "id": 29271333,
//     "node_id": "MDQ6VXNlcjI5MjcxMzMz",
//     "avatar_url": "https://avatars3.githubusercontent.com/u/29271333?v=4",
//     "gravatar_id": "",
//     "url": "https://api.github.com/users/newtonmunene99",
//     "html_url": "https://github.com/newtonmunene99",
//     "followers_url": "https://api.github.com/users/newtonmunene99/followers",
//     "following_url": "https://api.github.com/users/newtonmunene99/following{/other_user}",
//     "gists_url": "https://api.github.com/users/newtonmunene99/gists{/gist_id}",
//     "starred_url": "https://api.github.com/users/newtonmunene99/starred{/owner}{/repo}",
//     "subscriptions_url": "https://api.github.com/users/newtonmunene99/subscriptions",
//     "organizations_url": "https://api.github.com/users/newtonmunene99/orgs",
//     "repos_url": "https://api.github.com/users/newtonmunene99/repos",
//     "events_url": "https://api.github.com/users/newtonmunene99/events{/privacy}",
//     "received_events_url": "https://api.github.com/users/newtonmunene99/received_events",
//     "type": "User",
//     "site_admin": false
//   },
//   {
//     "login": "Sigilai5",
//     "id": 29841088,
//     "node_id": "MDQ6VXNlcjI5ODQxMDg4",
//     "avatar_url": "https://avatars0.githubusercontent.com/u/29841088?v=4",
//     "gravatar_id": "",
//     "url": "https://api.github.com/users/Sigilai5",
//     "html_url": "https://github.com/Sigilai5",
//     "followers_url": "https://api.github.com/users/Sigilai5/followers",
//     "following_url": "https://api.github.com/users/Sigilai5/following{/other_user}",
//     "gists_url": "https://api.github.com/users/Sigilai5/gists{/gist_id}",
//     "starred_url": "https://api.github.com/users/Sigilai5/starred{/owner}{/repo}",
//     "subscriptions_url": "https://api.github.com/users/Sigilai5/subscriptions",
//     "organizations_url": "https://api.github.com/users/Sigilai5/orgs",
//     "repos_url": "https://api.github.com/users/Sigilai5/repos",
//     "events_url": "https://api.github.com/users/Sigilai5/events{/privacy}",
//     "received_events_url": "https://api.github.com/users/Sigilai5/received_events",
//     "type": "User",
//     "site_admin": false
//   },
//   {
//     "login": "Manjoro",
//     "id": 30643359,
//     "node_id": "MDQ6VXNlcjMwNjQzMzU5",
//     "avatar_url": "https://avatars3.githubusercontent.com/u/30643359?v=4",
//     "gravatar_id": "",
//     "url": "https://api.github.com/users/Manjoro",
//     "html_url": "https://github.com/Manjoro",
//     "followers_url": "https://api.github.com/users/Manjoro/followers",
//     "following_url": "https://api.github.com/users/Manjoro/following{/other_user}",
//     "gists_url": "https://api.github.com/users/Manjoro/gists{/gist_id}",
//     "starred_url": "https://api.github.com/users/Manjoro/starred{/owner}{/repo}",
//     "subscriptions_url": "https://api.github.com/users/Manjoro/subscriptions",
//     "organizations_url": "https://api.github.com/users/Manjoro/orgs",
//     "repos_url": "https://api.github.com/users/Manjoro/repos",
//     "events_url": "https://api.github.com/users/Manjoro/events{/privacy}",
//     "received_events_url": "https://api.github.com/users/Manjoro/received_events",
//     "type": "User",
//     "site_admin": false
//   },
//   {
//     "login": "mzazakeith",
//     "id": 31074382,
//     "node_id": "MDQ6VXNlcjMxMDc0Mzgy",
//     "avatar_url": "https://avatars3.githubusercontent.com/u/31074382?v=4",
//     "gravatar_id": "",
//     "url": "https://api.github.com/users/mzazakeith",
//     "html_url": "https://github.com/mzazakeith",
//     "followers_url": "https://api.github.com/users/mzazakeith/followers",
//     "following_url": "https://api.github.com/users/mzazakeith/following{/other_user}",
//     "gists_url": "https://api.github.com/users/mzazakeith/gists{/gist_id}",
//     "starred_url": "https://api.github.com/users/mzazakeith/starred{/owner}{/repo}",
//     "subscriptions_url": "https://api.github.com/users/mzazakeith/subscriptions",
//     "organizations_url": "https://api.github.com/users/mzazakeith/orgs",
//     "repos_url": "https://api.github.com/users/mzazakeith/repos",
//     "events_url": "https://api.github.com/users/mzazakeith/events{/privacy}",
//     "received_events_url": "https://api.github.com/users/mzazakeith/received_events",
//     "type": "User",
//     "site_admin": false
//   },
//   {
//     "login": "Ben-Mbiyu",
//     "id": 33447829,
//     "node_id": "MDQ6VXNlcjMzNDQ3ODI5",
//     "avatar_url": "https://avatars3.githubusercontent.com/u/33447829?v=4",
//     "gravatar_id": "",
//     "url": "https://api.github.com/users/Ben-Mbiyu",
//     "html_url": "https://github.com/Ben-Mbiyu",
//     "followers_url": "https://api.github.com/users/Ben-Mbiyu/followers",
//     "following_url": "https://api.github.com/users/Ben-Mbiyu/following{/other_user}",
//     "gists_url": "https://api.github.com/users/Ben-Mbiyu/gists{/gist_id}",
//     "starred_url": "https://api.github.com/users/Ben-Mbiyu/starred{/owner}{/repo}",
//     "subscriptions_url": "https://api.github.com/users/Ben-Mbiyu/subscriptions",
//     "organizations_url": "https://api.github.com/users/Ben-Mbiyu/orgs",
//     "repos_url": "https://api.github.com/users/Ben-Mbiyu/repos",
//     "events_url": "https://api.github.com/users/Ben-Mbiyu/events{/privacy}",
//     "received_events_url": "https://api.github.com/users/Ben-Mbiyu/received_events",
//     "type": "User",
//     "site_admin": false
//   },
//   {
//     "login": "bochiedev",
//     "id": 35254431,
//     "node_id": "MDQ6VXNlcjM1MjU0NDMx",
//     "avatar_url": "https://avatars3.githubusercontent.com/u/35254431?v=4",
//     "gravatar_id": "",
//     "url": "https://api.github.com/users/bochiedev",
//     "html_url": "https://github.com/bochiedev",
//     "followers_url": "https://api.github.com/users/bochiedev/followers",
//     "following_url": "https://api.github.com/users/bochiedev/following{/other_user}",
//     "gists_url": "https://api.github.com/users/bochiedev/gists{/gist_id}",
//     "starred_url": "https://api.github.com/users/bochiedev/starred{/owner}{/repo}",
//     "subscriptions_url": "https://api.github.com/users/bochiedev/subscriptions",
//     "organizations_url": "https://api.github.com/users/bochiedev/orgs",
//     "repos_url": "https://api.github.com/users/bochiedev/repos",
//     "events_url": "https://api.github.com/users/bochiedev/events{/privacy}",
//     "received_events_url": "https://api.github.com/users/bochiedev/received_events",
//     "type": "User",
//     "site_admin": false
//   },
//   {
//     "login": "lupamo3",
//     "id": 35620770,
//     "node_id": "MDQ6VXNlcjM1NjIwNzcw",
//     "avatar_url": "https://avatars1.githubusercontent.com/u/35620770?v=4",
//     "gravatar_id": "",
//     "url": "https://api.github.com/users/lupamo3",
//     "html_url": "https://github.com/lupamo3",
//     "followers_url": "https://api.github.com/users/lupamo3/followers",
//     "following_url": "https://api.github.com/users/lupamo3/following{/other_user}",
//     "gists_url": "https://api.github.com/users/lupamo3/gists{/gist_id}",
//     "starred_url": "https://api.github.com/users/lupamo3/starred{/owner}{/repo}",
//     "subscriptions_url": "https://api.github.com/users/lupamo3/subscriptions",
//     "organizations_url": "https://api.github.com/users/lupamo3/orgs",
//     "repos_url": "https://api.github.com/users/lupamo3/repos",
//     "events_url": "https://api.github.com/users/lupamo3/events{/privacy}",
//     "received_events_url": "https://api.github.com/users/lupamo3/received_events",
//     "type": "User",
//     "site_admin": false
//   },
//   {
//     "login": "EugeneZnm",
//     "id": 35890744,
//     "node_id": "MDQ6VXNlcjM1ODkwNzQ0",
//     "avatar_url": "https://avatars1.githubusercontent.com/u/35890744?v=4",
//     "gravatar_id": "",
//     "url": "https://api.github.com/users/EugeneZnm",
//     "html_url": "https://github.com/EugeneZnm",
//     "followers_url": "https://api.github.com/users/EugeneZnm/followers",
//     "following_url": "https://api.github.com/users/EugeneZnm/following{/other_user}",
//     "gists_url": "https://api.github.com/users/EugeneZnm/gists{/gist_id}",
//     "starred_url": "https://api.github.com/users/EugeneZnm/starred{/owner}{/repo}",
//     "subscriptions_url": "https://api.github.com/users/EugeneZnm/subscriptions",
//     "organizations_url": "https://api.github.com/users/EugeneZnm/orgs",
//     "repos_url": "https://api.github.com/users/EugeneZnm/repos",
//     "events_url": "https://api.github.com/users/EugeneZnm/events{/privacy}",
//     "received_events_url": "https://api.github.com/users/EugeneZnm/received_events",
//     "type": "User",
//     "site_admin": false
//   },
//   {
//     "login": "kasambuli",
//     "id": 36161514,
//     "node_id": "MDQ6VXNlcjM2MTYxNTE0",
//     "avatar_url": "https://avatars3.githubusercontent.com/u/36161514?v=4",
//     "gravatar_id": "",
//     "url": "https://api.github.com/users/kasambuli",
//     "html_url": "https://github.com/kasambuli",
//     "followers_url": "https://api.github.com/users/kasambuli/followers",
//     "following_url": "https://api.github.com/users/kasambuli/following{/other_user}",
//     "gists_url": "https://api.github.com/users/kasambuli/gists{/gist_id}",
//     "starred_url": "https://api.github.com/users/kasambuli/starred{/owner}{/repo}",
//     "subscriptions_url": "https://api.github.com/users/kasambuli/subscriptions",
//     "organizations_url": "https://api.github.com/users/kasambuli/orgs",
//     "repos_url": "https://api.github.com/users/kasambuli/repos",
//     "events_url": "https://api.github.com/users/kasambuli/events{/privacy}",
//     "received_events_url": "https://api.github.com/users/kasambuli/received_events",
//     "type": "User",
//     "site_admin": false
//   },
//   {
//     "login": "Ashleyzawadi",
//     "id": 36164543,
//     "node_id": "MDQ6VXNlcjM2MTY0NTQz",
//     "avatar_url": "https://avatars0.githubusercontent.com/u/36164543?v=4",
//     "gravatar_id": "",
//     "url": "https://api.github.com/users/Ashleyzawadi",
//     "html_url": "https://github.com/Ashleyzawadi",
//     "followers_url": "https://api.github.com/users/Ashleyzawadi/followers",
//     "following_url": "https://api.github.com/users/Ashleyzawadi/following{/other_user}",
//     "gists_url": "https://api.github.com/users/Ashleyzawadi/gists{/gist_id}",
//     "starred_url": "https://api.github.com/users/Ashleyzawadi/starred{/owner}{/repo}",
//     "subscriptions_url": "https://api.github.com/users/Ashleyzawadi/subscriptions",
//     "organizations_url": "https://api.github.com/users/Ashleyzawadi/orgs",
//     "repos_url": "https://api.github.com/users/Ashleyzawadi/repos",
//     "events_url": "https://api.github.com/users/Ashleyzawadi/events{/privacy}",
//     "received_events_url": "https://api.github.com/users/Ashleyzawadi/received_events",
//     "type": "User",
//     "site_admin": false
//   },
//   {
//     "login": "zecollokaris",
//     "id": 36197725,
//     "node_id": "MDQ6VXNlcjM2MTk3NzI1",
//     "avatar_url": "https://avatars2.githubusercontent.com/u/36197725?v=4",
//     "gravatar_id": "",
//     "url": "https://api.github.com/users/zecollokaris",
//     "html_url": "https://github.com/zecollokaris",
//     "followers_url": "https://api.github.com/users/zecollokaris/followers",
//     "following_url": "https://api.github.com/users/zecollokaris/following{/other_user}",
//     "gists_url": "https://api.github.com/users/zecollokaris/gists{/gist_id}",
//     "starred_url": "https://api.github.com/users/zecollokaris/starred{/owner}{/repo}",
//     "subscriptions_url": "https://api.github.com/users/zecollokaris/subscriptions",
//     "organizations_url": "https://api.github.com/users/zecollokaris/orgs",
//     "repos_url": "https://api.github.com/users/zecollokaris/repos",
//     "events_url": "https://api.github.com/users/zecollokaris/events{/privacy}",
//     "received_events_url": "https://api.github.com/users/zecollokaris/received_events",
//     "type": "User",
//     "site_admin": false
//   },
//   {
//     "login": "Ianodad",
//     "id": 37324216,
//     "node_id": "MDQ6VXNlcjM3MzI0MjE2",
//     "avatar_url": "https://avatars0.githubusercontent.com/u/37324216?v=4",
//     "gravatar_id": "",
//     "url": "https://api.github.com/users/Ianodad",
//     "html_url": "https://github.com/Ianodad",
//     "followers_url": "https://api.github.com/users/Ianodad/followers",
//     "following_url": "https://api.github.com/users/Ianodad/following{/other_user}",
//     "gists_url": "https://api.github.com/users/Ianodad/gists{/gist_id}",
//     "starred_url": "https://api.github.com/users/Ianodad/starred{/owner}{/repo}",
//     "subscriptions_url": "https://api.github.com/users/Ianodad/subscriptions",
//     "organizations_url": "https://api.github.com/users/Ianodad/orgs",
//     "repos_url": "https://api.github.com/users/Ianodad/repos",
//     "events_url": "https://api.github.com/users/Ianodad/events{/privacy}",
//     "received_events_url": "https://api.github.com/users/Ianodad/received_events",
//     "type": "User",
//     "site_admin": false
//   },
//   {
//     "login": "Sarah-Marion",
//     "id": 37328207,
//     "node_id": "MDQ6VXNlcjM3MzI4MjA3",
//     "avatar_url": "https://avatars2.githubusercontent.com/u/37328207?v=4",
//     "gravatar_id": "",
//     "url": "https://api.github.com/users/Sarah-Marion",
//     "html_url": "https://github.com/Sarah-Marion",
//     "followers_url": "https://api.github.com/users/Sarah-Marion/followers",
//     "following_url": "https://api.github.com/users/Sarah-Marion/following{/other_user}",
//     "gists_url": "https://api.github.com/users/Sarah-Marion/gists{/gist_id}",
//     "starred_url": "https://api.github.com/users/Sarah-Marion/starred{/owner}{/repo}",
//     "subscriptions_url": "https://api.github.com/users/Sarah-Marion/subscriptions",
//     "organizations_url": "https://api.github.com/users/Sarah-Marion/orgs",
//     "repos_url": "https://api.github.com/users/Sarah-Marion/repos",
//     "events_url": "https://api.github.com/users/Sarah-Marion/events{/privacy}",
//     "received_events_url": "https://api.github.com/users/Sarah-Marion/received_events",
//     "type": "User",
//     "site_admin": false
//   },
//   {
//     "login": "Monroe100",
//     "id": 37328635,
//     "node_id": "MDQ6VXNlcjM3MzI4NjM1",
//     "avatar_url": "https://avatars3.githubusercontent.com/u/37328635?v=4",
//     "gravatar_id": "",
//     "url": "https://api.github.com/users/Monroe100",
//     "html_url": "https://github.com/Monroe100",
//     "followers_url": "https://api.github.com/users/Monroe100/followers",
//     "following_url": "https://api.github.com/users/Monroe100/following{/other_user}",
//     "gists_url": "https://api.github.com/users/Monroe100/gists{/gist_id}",
//     "starred_url": "https://api.github.com/users/Monroe100/starred{/owner}{/repo}",
//     "subscriptions_url": "https://api.github.com/users/Monroe100/subscriptions",
//     "organizations_url": "https://api.github.com/users/Monroe100/orgs",
//     "repos_url": "https://api.github.com/users/Monroe100/repos",
//     "events_url": "https://api.github.com/users/Monroe100/events{/privacy}",
//     "received_events_url": "https://api.github.com/users/Monroe100/received_events",
//     "type": "User",
//     "site_admin": false
//   },
//   {
//     "login": "kd-kinuthiadavid",
//     "id": 38416188,
//     "node_id": "MDQ6VXNlcjM4NDE2MTg4",
//     "avatar_url": "https://avatars3.githubusercontent.com/u/38416188?v=4",
//     "gravatar_id": "",
//     "url": "https://api.github.com/users/kd-kinuthiadavid",
//     "html_url": "https://github.com/kd-kinuthiadavid",
//     "followers_url": "https://api.github.com/users/kd-kinuthiadavid/followers",
//     "following_url": "https://api.github.com/users/kd-kinuthiadavid/following{/other_user}",
//     "gists_url": "https://api.github.com/users/kd-kinuthiadavid/gists{/gist_id}",
//     "starred_url": "https://api.github.com/users/kd-kinuthiadavid/starred{/owner}{/repo}",
//     "subscriptions_url": "https://api.github.com/users/kd-kinuthiadavid/subscriptions",
//     "organizations_url": "https://api.github.com/users/kd-kinuthiadavid/orgs",
//     "repos_url": "https://api.github.com/users/kd-kinuthiadavid/repos",
//     "events_url": "https://api.github.com/users/kd-kinuthiadavid/events{/privacy}",
//     "received_events_url": "https://api.github.com/users/kd-kinuthiadavid/received_events",
//     "type": "User",
//     "site_admin": false
//   },
//   {
//     "login": "Benard18",
//     "id": 38454352,
//     "node_id": "MDQ6VXNlcjM4NDU0MzUy",
//     "avatar_url": "https://avatars0.githubusercontent.com/u/38454352?v=4",
//     "gravatar_id": "",
//     "url": "https://api.github.com/users/Benard18",
//     "html_url": "https://github.com/Benard18",
//     "followers_url": "https://api.github.com/users/Benard18/followers",
//     "following_url": "https://api.github.com/users/Benard18/following{/other_user}",
//     "gists_url": "https://api.github.com/users/Benard18/gists{/gist_id}",
//     "starred_url": "https://api.github.com/users/Benard18/starred{/owner}{/repo}",
//     "subscriptions_url": "https://api.github.com/users/Benard18/subscriptions",
//     "organizations_url": "https://api.github.com/users/Benard18/orgs",
//     "repos_url": "https://api.github.com/users/Benard18/repos",
//     "events_url": "https://api.github.com/users/Benard18/events{/privacy}",
//     "received_events_url": "https://api.github.com/users/Benard18/received_events",
//     "type": "User",
//     "site_admin": false
//   },
//   {
//     "login": "Kaundu",
//     "id": 38455020,
//     "node_id": "MDQ6VXNlcjM4NDU1MDIw",
//     "avatar_url": "https://avatars3.githubusercontent.com/u/38455020?v=4",
//     "gravatar_id": "",
//     "url": "https://api.github.com/users/Kaundu",
//     "html_url": "https://github.com/Kaundu",
//     "followers_url": "https://api.github.com/users/Kaundu/followers",
//     "following_url": "https://api.github.com/users/Kaundu/following{/other_user}",
//     "gists_url": "https://api.github.com/users/Kaundu/gists{/gist_id}",
//     "starred_url": "https://api.github.com/users/Kaundu/starred{/owner}{/repo}",
//     "subscriptions_url": "https://api.github.com/users/Kaundu/subscriptions",
//     "organizations_url": "https://api.github.com/users/Kaundu/orgs",
//     "repos_url": "https://api.github.com/users/Kaundu/repos",
//     "events_url": "https://api.github.com/users/Kaundu/events{/privacy}",
//     "received_events_url": "https://api.github.com/users/Kaundu/received_events",
//     "type": "User",
//     "site_admin": false
//   },
//   {
//     "login": "Evohmike",
//     "id": 38455539,
//     "node_id": "MDQ6VXNlcjM4NDU1NTM5",
//     "avatar_url": "https://avatars0.githubusercontent.com/u/38455539?v=4",
//     "gravatar_id": "",
//     "url": "https://api.github.com/users/Evohmike",
//     "html_url": "https://github.com/Evohmike",
//     "followers_url": "https://api.github.com/users/Evohmike/followers",
//     "following_url": "https://api.github.com/users/Evohmike/following{/other_user}",
//     "gists_url": "https://api.github.com/users/Evohmike/gists{/gist_id}",
//     "starred_url": "https://api.github.com/users/Evohmike/starred{/owner}{/repo}",
//     "subscriptions_url": "https://api.github.com/users/Evohmike/subscriptions",
//     "organizations_url": "https://api.github.com/users/Evohmike/orgs",
//     "repos_url": "https://api.github.com/users/Evohmike/repos",
//     "events_url": "https://api.github.com/users/Evohmike/events{/privacy}",
//     "received_events_url": "https://api.github.com/users/Evohmike/received_events",
//     "type": "User",
//     "site_admin": false
//   },
//   {
//     "login": "maxwellharon",
//     "id": 38457443,
//     "node_id": "MDQ6VXNlcjM4NDU3NDQz",
//     "avatar_url": "https://avatars0.githubusercontent.com/u/38457443?v=4",
//     "gravatar_id": "",
//     "url": "https://api.github.com/users/maxwellharon",
//     "html_url": "https://github.com/maxwellharon",
//     "followers_url": "https://api.github.com/users/maxwellharon/followers",
//     "following_url": "https://api.github.com/users/maxwellharon/following{/other_user}",
//     "gists_url": "https://api.github.com/users/maxwellharon/gists{/gist_id}",
//     "starred_url": "https://api.github.com/users/maxwellharon/starred{/owner}{/repo}",
//     "subscriptions_url": "https://api.github.com/users/maxwellharon/subscriptions",
//     "organizations_url": "https://api.github.com/users/maxwellharon/orgs",
//     "repos_url": "https://api.github.com/users/maxwellharon/repos",
//     "events_url": "https://api.github.com/users/maxwellharon/events{/privacy}",
//     "received_events_url": "https://api.github.com/users/maxwellharon/received_events",
//     "type": "User",
//     "site_admin": false
//   },
//   {
//     "login": "paulettemaina",
//     "id": 38458956,
//     "node_id": "MDQ6VXNlcjM4NDU4OTU2",
//     "avatar_url": "https://avatars1.githubusercontent.com/u/38458956?v=4",
//     "gravatar_id": "",
//     "url": "https://api.github.com/users/paulettemaina",
//     "html_url": "https://github.com/paulettemaina",
//     "followers_url": "https://api.github.com/users/paulettemaina/followers",
//     "following_url": "https://api.github.com/users/paulettemaina/following{/other_user}",
//     "gists_url": "https://api.github.com/users/paulettemaina/gists{/gist_id}",
//     "starred_url": "https://api.github.com/users/paulettemaina/starred{/owner}{/repo}",
//     "subscriptions_url": "https://api.github.com/users/paulettemaina/subscriptions",
//     "organizations_url": "https://api.github.com/users/paulettemaina/orgs",
//     "repos_url": "https://api.github.com/users/paulettemaina/repos",
//     "events_url": "https://api.github.com/users/paulettemaina/events{/privacy}",
//     "received_events_url": "https://api.github.com/users/paulettemaina/received_events",
//     "type": "User",
//     "site_admin": false
//   },
//   {
//     "login": "vonmutinda",
//     "id": 38462734,
//     "node_id": "MDQ6VXNlcjM4NDYyNzM0",
//     "avatar_url": "https://avatars0.githubusercontent.com/u/38462734?v=4",
//     "gravatar_id": "",
//     "url": "https://api.github.com/users/vonmutinda",
//     "html_url": "https://github.com/vonmutinda",
//     "followers_url": "https://api.github.com/users/vonmutinda/followers",
//     "following_url": "https://api.github.com/users/vonmutinda/following{/other_user}",
//     "gists_url": "https://api.github.com/users/vonmutinda/gists{/gist_id}",
//     "starred_url": "https://api.github.com/users/vonmutinda/starred{/owner}{/repo}",
//     "subscriptions_url": "https://api.github.com/users/vonmutinda/subscriptions",
//     "organizations_url": "https://api.github.com/users/vonmutinda/orgs",
//     "repos_url": "https://api.github.com/users/vonmutinda/repos",
//     "events_url": "https://api.github.com/users/vonmutinda/events{/privacy}",
//     "received_events_url": "https://api.github.com/users/vonmutinda/received_events",
//     "type": "User",
//     "site_admin": false
//   },
//   {
//     "login": "Anillab",
//     "id": 38463007,
//     "node_id": "MDQ6VXNlcjM4NDYzMDA3",
//     "avatar_url": "https://avatars2.githubusercontent.com/u/38463007?v=4",
//     "gravatar_id": "",
//     "url": "https://api.github.com/users/Anillab",
//     "html_url": "https://github.com/Anillab",
//     "followers_url": "https://api.github.com/users/Anillab/followers",
//     "following_url": "https://api.github.com/users/Anillab/following{/other_user}",
//     "gists_url": "https://api.github.com/users/Anillab/gists{/gist_id}",
//     "starred_url": "https://api.github.com/users/Anillab/starred{/owner}{/repo}",
//     "subscriptions_url": "https://api.github.com/users/Anillab/subscriptions",
//     "organizations_url": "https://api.github.com/users/Anillab/orgs",
//     "repos_url": "https://api.github.com/users/Anillab/repos",
//     "events_url": "https://api.github.com/users/Anillab/events{/privacy}",
//     "received_events_url": "https://api.github.com/users/Anillab/received_events",
//     "type": "User",
//     "site_admin": false
//   },
//   {
//     "login": "marvinChomba",
//     "id": 40211183,
//     "node_id": "MDQ6VXNlcjQwMjExMTgz",
//     "avatar_url": "https://avatars2.githubusercontent.com/u/40211183?v=4",
//     "gravatar_id": "",
//     "url": "https://api.github.com/users/marvinChomba",
//     "html_url": "https://github.com/marvinChomba",
//     "followers_url": "https://api.github.com/users/marvinChomba/followers",
//     "following_url": "https://api.github.com/users/marvinChomba/following{/other_user}",
//     "gists_url": "https://api.github.com/users/marvinChomba/gists{/gist_id}",
//     "starred_url": "https://api.github.com/users/marvinChomba/starred{/owner}{/repo}",
//     "subscriptions_url": "https://api.github.com/users/marvinChomba/subscriptions",
//     "organizations_url": "https://api.github.com/users/marvinChomba/orgs",
//     "repos_url": "https://api.github.com/users/marvinChomba/repos",
//     "events_url": "https://api.github.com/users/marvinChomba/events{/privacy}",
//     "received_events_url": "https://api.github.com/users/marvinChomba/received_events",
//     "type": "User",
//     "site_admin": false
//   },
//   {
//     "login": "HarryThuku",
//     "id": 40566766,
//     "node_id": "MDQ6VXNlcjQwNTY2NzY2",
//     "avatar_url": "https://avatars1.githubusercontent.com/u/40566766?v=4",
//     "gravatar_id": "",
//     "url": "https://api.github.com/users/HarryThuku",
//     "html_url": "https://github.com/HarryThuku",
//     "followers_url": "https://api.github.com/users/HarryThuku/followers",
//     "following_url": "https://api.github.com/users/HarryThuku/following{/other_user}",
//     "gists_url": "https://api.github.com/users/HarryThuku/gists{/gist_id}",
//     "starred_url": "https://api.github.com/users/HarryThuku/starred{/owner}{/repo}",
//     "subscriptions_url": "https://api.github.com/users/HarryThuku/subscriptions",
//     "organizations_url": "https://api.github.com/users/HarryThuku/orgs",
//     "repos_url": "https://api.github.com/users/HarryThuku/repos",
//     "events_url": "https://api.github.com/users/HarryThuku/events{/privacy}",
//     "received_events_url": "https://api.github.com/users/HarryThuku/received_events",
//     "type": "User",
//     "site_admin": false
//   },
//   {
//     "login": "Jeffmusa",
//     "id": 40592653,
//     "node_id": "MDQ6VXNlcjQwNTkyNjUz",
//     "avatar_url": "https://avatars0.githubusercontent.com/u/40592653?v=4",
//     "gravatar_id": "",
//     "url": "https://api.github.com/users/Jeffmusa",
//     "html_url": "https://github.com/Jeffmusa",
//     "followers_url": "https://api.github.com/users/Jeffmusa/followers",
//     "following_url": "https://api.github.com/users/Jeffmusa/following{/other_user}",
//     "gists_url": "https://api.github.com/users/Jeffmusa/gists{/gist_id}",
//     "starred_url": "https://api.github.com/users/Jeffmusa/starred{/owner}{/repo}",
//     "subscriptions_url": "https://api.github.com/users/Jeffmusa/subscriptions",
//     "organizations_url": "https://api.github.com/users/Jeffmusa/orgs",
//     "repos_url": "https://api.github.com/users/Jeffmusa/repos",
//     "events_url": "https://api.github.com/users/Jeffmusa/events{/privacy}",
//     "received_events_url": "https://api.github.com/users/Jeffmusa/received_events",
//     "type": "User",
//     "site_admin": false
//   }
// ];

const defaultFollowing = [];
// userFollowing
const initialState = {
  following: defaultFollowing,
  isFetching: false,
  hasError: false
};

function userFollowingReducer(state=initialState, action){
  switch (action.type) {
    case 'GET_USER_FOLLOWING_INFO':
      return {
        ...state,
        hasError: false,
        following: [],
        isFetching: true
      };
    case 'USER_FOLLOWING_RESULTS':
      return {
        ...state,
        following: action.data,
        isFetching: false,
      };
    case 'USER_FOLLOWING_ERROR':
      return {
        ...state,
        following: [],
        isFetching: false,
        hasError: true
      };
    default:
      return state
  }
}

export default userFollowingReducer;